run_on_failure: Capture Page Screenshot
web_url: https://id.atlassian.com/login
#web_url: https://testbase.atlassian.net/jira/dashboards/last-visited
#web_url: https://opensource-demo.orangehrmlive.com/

user: mail.for.testbase@gmail.com
password: 135onk086